language: php

matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: STATIC_ANALYSIS=true

install: composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - |
    if [[ $STATIC_ANALYSIS == true ]]; then
      composer require --ignore-platform-reqs --dev phpstan/phpstan
      vendor/bin/phpstan analyze src -c phpstan.neon -l 1
    fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - portey@gmail.com
      - a@viniychuk.com
    on_success: change
    on_failure: always
